In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import numpy as np

In [2]:
data = load_breast_cancer()
X, y = data['data'], data['target']

In [3]:
X.shape, y.shape

((569, 30), (569,))

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
model = GaussianNB()
model.fit(X_train, y_train)
print('The model is trained!')

The model is trained!


In [6]:
y_pred = model.predict(X_test)

In [7]:
y_pred, y_test

(array([1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
        1, 1, 1, 0]),
 array([1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
        1, 1, 1, 0]))

In [8]:
from sklearn import metrics
def classification_metrics(target, pred):
    tn, fp, fn, tp = metrics.confusion_matrix(target, pred).ravel()
    acc = (tn + tp) / (tn + fp +fn + tp)
    sen = tp / (tp + fn)
    spc = tn / (tn + fp)
    prc = tp / (tp + fp)
    return acc, sen, spc, prc

In [9]:
classification_metrics(y_test, y_pred)

(0.9385964912280702,
 0.9571428571428572,
 0.9090909090909091,
 0.9436619718309859)

In [10]:
model.class_prior_

array([0.36923077, 0.63076923])

In [16]:
prob = model.predict_proba(X_test)[:,1]


array([1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 6.12366888e-040,
       1.67031420e-008, 1.00000000e+000, 9.99999996e-001, 8.55052860e-049,
       1.00000000e+000, 5.60854811e-018, 9.99999756e-001, 1.00000000e+000,
       3.29314368e-050, 6.33988573e-008, 1.00000000e+000, 9.86302668e-001,
       3.17616427e-001, 5.34995471e-019, 1.28089906e-007, 1.00000000e+000,
       2.04706311e-008, 9.99966842e-001, 4.59977712e-006, 1.00000000e+000,
       1.52164512e-041, 9.36429210e-078, 1.60152771e-020, 1.00000000e+000,
       4.33445941e-002, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
       1.00000000e+000, 1.00000000e+000, 1.23276862e-054, 2.67078775e-038,
       9.99999776e-001, 4.03848336e-228, 1.00000000e+000, 9.99999983e-001,
       9.99999994e-001, 9.99999643e-001, 9.07870790e-014, 1.00000000e+000,
       2.72867974e-100, 9.84895213e-001, 1.00000000e+000, 1.00000000e+000,
       1.00000000e+000, 1.72555134e-019, 1.00000000e+000, 1.00000000e+000,
       9.99971225e-001, 2

In [17]:
from sklearn import metrics

In [18]:
metrics.roc_auc_score(y_test, prob)

0.9915584415584415